import { CustomButton } from "common/button.slint";
import { Colors } from "../styles/colors.slint";
import { ScrollView } from "std-widgets.slint";

export component BackLogView {
    in property <length> container-width;
    in property <length> container-height;
    in property <[{ speaker: string, text: string }]> backlogs;
    property <int> backlog_len: backlogs.length;

    callback back();
    callback backlog-change(int);

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.overlay-background;

        // 返回按钮
        CustomButton {
            x: parent.width * 0.06;
            y: parent.height * 0.04;
            text: "返回游戏";
            button-width: parent.width * 0.10;
            button-height: parent.height * 0.06;
            font-size: parent.height * 0.06 * 0.4;
            clicked => { root.back(); }
        }

        Rectangle {
            width: parent.width * 0.8;
            height: parent.height * 0.8;

            for len in backlog_len : Text {
                property <{ speaker: string, text: string }> item: backlogs[len];
                text: item.speaker + ": " + item.text;
                color: white;
                wrap: word-wrap;
                font-size: parent.height * 0.06;
                x: 0;
                y: len * 2 * parent.height * 0.06;
            }
        }


        TouchArea {
            scroll-event(event) => {
                if(event.delta-y == 0) {
                    reject
                }
                if(event.delta-y > 0) {
                    root.backlog-change(1);
                } else {
                    root.backlog-change(-1);
                }
                accept
            }
        }
    }
}