import { CustomButton } from "common/button.slint";
import { Colors } from "../styles/colors.slint";
import { ScrollView } from "std-widgets.slint";

export component BackLogView {
    in property <length> container-width;
    in property <length> container-height;
    in property <[{ front: string, back: string, script: string, index: int }]> backlogs;
    property <int> backlog_len: backlogs.length;

    callback back();
    callback backlog-change(int);
    callback backlog-jump(string, int);

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.overlay-background;

        // 返回按钮
        CustomButton {
            x: parent.width * 0.06;
            y: parent.height * 0.04;
            text: "返回游戏";
            button-width: parent.width * 0.10;
            button-height: parent.height * 0.06;
            font-size: parent.height * 0.06 * 0.4;
            clicked => { root.back(); }
        }

        TouchArea {
                    y: 0.1 * parent.height;
                    height: 0.9 * parent.height;
                    scroll-event(event) => {
                        if(event.delta-y == 0) {
                            reject
                        }
                        if(event.delta-y > 0) {
                            root.backlog-change(1);
                        } else {
                            root.backlog-change(-1);
                        }
                        reject
                    }
                }

        Rectangle {
            width: parent.width * 0.8;
            height: parent.height * 0.8;

            for len in backlog_len : Rectangle {
                property <{ front: string, back: string, script: string, index: int }> item: backlogs[len];
                height: parent.height * 0.06 * 4;
                y: len * 4.2 * parent.height * 0.06;

                TouchArea {
                    height: parent.height * 0.28;
                    width: parent.width * 31 / 32;
                    x: 0;
                    y: 0;
                    clicked => {
                        root.backlog-jump(item.script, item.index);
                    }
                }

                Text {
                    height: parent.height * 0.28;
                    width: parent.width * 31 / 32;
                    text: item.front;
                    color: white;
                    wrap: word-wrap;
                    font-size: parent.height * 0.15;
                    x: 0;
                    y: 0;
                }

                Text {
                    height: parent.height * 0.72;
                    width: parent.width * 31 / 32;
                    text: item.back;
                    color: white;
                    wrap: word-wrap;
                    font-size: parent.height * 0.18;
                    x: 0;
                    y: parent.height * 0.28;
                }
            }
        }
    }
}