import { CustomButton } from "common/button.slint";
import { Colors } from "../styles/colors.slint";

export struct ExItem {
    indexs:int,
    bg:[image],
    is_lock:bool,
}

export component Extra {
    in property <ExItem> ex-item;

    callback print(ExItem);

    Rectangle {
        background: Colors.border-color;

        Image {
            source: ex-item.bg[0];
            width: parent.width;
            height: parent.height;
        }
    }

    if !ex-item.is-lock: TouchArea {
        clicked => { root.print(ex-item); }
    }
}

export component ExtraView {
    in property <length> container-width;
    in property <length> container-height;
    in property <[ExItem]> ex-items;
    property <ExItem> images;
    property <int> viewing_index: 0;
    property <bool> is_viewing: false;
    callback back();

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.slider-background;

        if root.is_viewing: Image {
            source: images.bg[viewing_index];
            width: parent.width;
            height: parent.height;

            TouchArea {
                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        if (event.button == PointerEventButton.left) {
                            if (viewing_index + 1 < images.indexs) {
                                viewing_index += 1;
                            } else {
                                root.is_viewing = false;
                                viewing_index = 0;
                            }
                        } else if (event.button == PointerEventButton.right) {
                            root.is_viewing = false;
                            viewing_index = 0;
                        }
                    }
                }
            }
        }

        // 返回按钮
        if !root.is_viewing: CustomButton {
            x: parent.width * 0.073;
            y: parent.height * 0.04;
            text: "返回游戏";
            button-width: parent.width * 0.10;
            button-height: parent.height * 0.06;
            font-size: parent.width * 0.0135;
            clicked => { root.back(); }
        }

        if !root.is_viewing: Rectangle {
            x: parent.width * 0.05;
            y: parent.height * 0.12;
            width: parent.width * 0.88;
            height: parent.height * 0.85;

            for ei[i] in ex-items: Extra {
                y: (Math.floor(i / 4)) * 21.625 / 85 * parent.height;
                x: (Math.mod(i, 4)) * 24 / 88 * parent.width;
                width: 18 / 88 * parent.width;
                height: 10.125 / 85 * parent.height / 9 * 16;
                ex-item: ei;
                print(item) => {
                    root.images = item;
                    root.is_viewing = true;
                }
            }
        }
    }
}

