import { CustomButton } from "common/button.slint";
import { Colors } from "../styles/colors.slint";
import { Save, SaveItem } from "save.slint";

export component LoadView {
    in property <length> container-width;
    in property <length> container-height;
    in property <[SaveItem]> save-items;

    callback back();
    callback load(string, int);

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.light-purple;

        // 返回按钮
        CustomButton {
            x: parent.width * 0.073;
            y: parent.height * 0.04;
            text: "返回游戏";
            button-width: parent.width * 0.10;
            button-height: parent.height * 0.06;
            font-size: parent.width * 0.0135;
            clicked => { root.back(); }
        }

        Rectangle {
            x: parent.width * 0.05;
            y: parent.height * 0.12;
            width: parent.width * 0.88;
            height: parent.height * 0.85;

            for si[i] in save-items :Save {
                y: (Math.floor(i / 4)) * 21.625 / 85 * parent.height;
                x: (Math.mod(i, 4)) * 24 / 88 * parent.width;
                width: 18 / 88 * parent.width;
                height: 10.125 / 85 * parent.height / 9 * 16;
                save-item: si;
                clicked => { load(si.name, si.index) }
            }
        }
    }
}

