import { CustomButton } from "common/button.slint";
import { Colors } from "../styles/colors.slint";

export struct SaveItem {
    name: string,
    index: int,
    bg: image,
    explain: string,
}

export component Save {
    in property <SaveItem> save-item;

    callback clicked();

    Rectangle {
        background: Colors.border-color;

        Image {
            source: save-item.bg;
            width: parent.width;
            height: parent.height;
        }

        Rectangle {
            y: parent.height * 0.7;
            height: parent.height * 0.3;
            background: Colors.overlay-background;

            Text {
                text: save-item.explain;
                font-size: parent.height * 0.7;
                color: Colors.text-light;
            }
        }
    }

    TouchArea {
        clicked => { root.clicked(); }
    }
}

export component SaveView {
    in property <length> container-width;
    in property <length> container-height;
    in property <[[SaveItem]]> save-items;
    property <int> page-size: 10;
    property <int> page-num: 1;

    callback back();
    callback save(int, int);

    Rectangle {
        width: container-width;
        height: container-height;
        background: Colors.slider-background;

        // 返回按钮
        CustomButton {
            x: parent.width * 0.073;
            y: parent.height * 0.04;
            text: "返回游戏";
            button-width: parent.width * 0.10;
            button-height: parent.height * 0.06;
            font-size: parent.width * 0.0135;
            clicked => { root.back(); }
        }

        for i in page-size: CustomButton {
            x: parent.width * (0.96 - 0.04 * (page-size - i));
            y: parent.height * 0.04;
            text: i + 1;
            button-width: parent.width * 0.03;
            button-height: parent.height * 0.06;
            font-size: parent.width * 0.0135;
            is-on: i + 1 == page-num;
            clicked => { page-num = i + 1 }
        }

        Rectangle {
            x: parent.width * 0.05;
            y: parent.height * 0.12;
            width: parent.width * 0.88;
            height: parent.height * 0.85;

            for si[i] in save-items[page-num - 1]: Save {
                y: (Math.floor(i / 4)) * 21.625 / 85 * parent.height;
                x: (Math.mod(i, 4)) * 24 / 88 * parent.width;
                width: 18 / 88 * parent.width;
                height: 10.125 / 85 * parent.height / 9 * 16;
                save-item: si;
                clicked => { save(i, page-num - 1) }
            }
        }
    }
}

