// 定义全局颜色常量
export global Colors {
    out property <color> button-background: #6c757d;
    out property <color> button-text: white;
    out property <color> overlay-background: #000a;
    out property <color> text-primary: #333;
    out property <color> text-light: white;
    out property <color> slider-background: #ddd;
    out property <color> border-color: #ccc;
    out property <color> light-purple: #E0D0FF;
}