import { SwitchToggle } from "../common/switch_toggle.slint";

export component ScreenConfig {
    in property <bool> is-fullscreen;

    callback toggle-fullscreen();

    Rectangle {
        SwitchToggle {
            x: parent.width * 0.02;
            y: 0;
            width: parent.width * 0.35;
            height: parent.height * 0.03;
            label: "全屏开关";
            texts: 6;
            checked: root.is-fullscreen;
            toggled => {
                root.toggle-fullscreen();
            }
        }
    }
}
