import { VolumeSlider } from "../common/volume_slider.slint";
import { SwitchToggle } from "../common/switch_toggle.slint";

export component SystemConfig {
    in-out property <bool> is-wait;
    in-out property <float> delay;

    Rectangle {
        SwitchToggle {
            x: parent.width * 0.02;
            y: 0;
            width: parent.width * 0.35;
            height: parent.height * 0.035;
            label: "自动等待语音";
            texts: 6;
            checked <=> root.is-wait;
        }

        VolumeSlider {
            y: parent.height * 0.08;
            x: parent.width * 0.02;
            width: parent.width * 0.35;
            height: parent.height * 0.035;
            max: 5.0;
            min: 1.0;
            label: "自动等待时长";
            texts: 6;
            volume: root.delay;
            volume-changed(value) => {
                root.delay = value;
            }
        }
    }
}