import { CustomButton } from "../common/button.slint";
import { VolumeSlider } from "../common/volume_slider.slint";
import { Colors } from "../../styles/colors.slint";
import { Switch } from "std-widgets.slint";

export component TextConfig {
    in-out property <float> text-speed;
    in-out property <float> dialogue-opacity;
    in-out property <bool> is-bold;
    in-out property <bool> show-shadow;
    
    callback volume-changed();
    callback voice-volume-changed();

    // 设置面板
    Rectangle {
        VolumeSlider {
            y: 0;
            x: parent.width * 0.02;
            width: parent.width * 0.35;
            height: parent.height * 0.035;
            label: "文本速度";
            volume: root.text-speed;
            texts: 6;
            volume-changed(value) => {
                root.text-speed = value;
            }
        }

        VolumeSlider {
            y: parent.height * 0.08;
            x: parent.width * 0.02;
            width: parent.width * 0.35;
            height: parent.height * 0.035;
            label: "对话框透明度";
            texts: 6;
            min: 0;
            max: 1;
            volume: root.dialogue-opacity;
            volume-changed(value) => {
                root.dialogue-opacity = value;
            }
        }

        Text {
            y: parent.height * 0.16;
            x: parent.width * 0.02;
            width: parent.width * 0.35;
            height: parent.height * 0.035;
            text: "文本加粗";
            font-size: parent.height * 0.035 * 0.8;
            color: Colors.text-light;
        }

        Switch {
            y: parent.height * 0.16;
            x: parent.height * 0.252 + parent.width * 0.02;
            checked <=> root.is-bold;
        }

        Text {
            y: parent.height * 0.24;
            x: parent.width * 0.02;
            text: "文本阴影";
            font-size: parent.height * 0.035 * 0.8;
            color: Colors.text-light;
        }

        Switch {
            y: parent.height * 0.24;
            x: parent.height * 0.252 + parent.width * 0.02;
            checked <=> root.show-shadow;
        }
    }
}
