[initialize]
script_path = "./source/script/"
background_path = "./source/background/"
cg_path = "./source/cg/"
voice_path = "./source/voice/"
bgm_path = "./source/bgm/"
figure_path = "./source/figure/"
video_path = "./source/video/"
video_extension = "mp4"
save_path = "./savedata/"

[character]
"rir" = "聖莉々子"
"rar" = "美倉礼良"
