export component MainWindow inherits Window {
    in property<string> dialogue;
    in property<string> speaker;
    in property<image> bg;

    width: 1280px;
    height: 720px;
    title: "KiteVN";

    //背景图（可替换）
    Image {
        source: bg;
        width: parent.width;
        height: parent.height;
    }

    // 半透明的对话框背景
    Rectangle {
        y: parent.height - 200px;
        width: parent.width;
        height: 200px;
        background: #0008; // 半透明黑色
    }
    // 对话文本
    Text {
        text: root.speaker + ": " + root.dialogue;
        x: 20px;
        y: parent.height - 180px;
        font-size: 24px;
        color: white;
    }

    // 鼠标点击区域（全屏）
    TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {root.clicked()}
    }

    // 状态绑定属性和事件
    callback clicked();
}
